# Form implementation generated from reading ui file 'add_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddDialog(object):
    def setupUi(self, AddDialog):
        AddDialog.setObjectName("AddDialog")
        AddDialog.resize(400, 654)
        AddDialog.setMinimumSize(QtCore.QSize(400, 654))
        AddDialog.setMaximumSize(QtCore.QSize(400, 654))
        AddDialog.setStyleSheet("")
        self.widget = QtWidgets.QWidget(AddDialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 400, 654))
        self.widget.setStyleSheet("QWidget#widget{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 72, 72, 255), stop:1 rgba(136, 129, 255, 255));\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 140, 0, 255), stop:1 rgba(0, 212, 255, 255));\n"
"    border: 2px solid #85efff;\n"
"    border-radius: 15px;    \n"
"    color: rgb(255, 255, 255);\n"
"    font-family: roboto;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 255, 115, 255), stop:1 rgba(184, 255, 73, 255));\n"
"    border: 2px solid #90ff94;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    border-radius: 15px;\n"
"    font-family: roboto;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.addButton = QtWidgets.QPushButton(self.widget)
        self.addButton.setGeometry(QtCore.QRect(110, 590, 201, 41))
        self.addButton.setObjectName("addButton")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(30, 390, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.directorEdit = QtWidgets.QLineEdit(self.widget)
        self.directorEdit.setGeometry(QtCore.QRect(30, 430, 341, 31))
        font = QtGui.QFont()
        font.setFamily("roboto")
        font.setPointSize(-1)
        self.directorEdit.setFont(font)
        self.directorEdit.setObjectName("directorEdit")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(30, 290, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nameEdit = QtWidgets.QLineEdit(self.widget)
        self.nameEdit.setGeometry(QtCore.QRect(30, 60, 341, 31))
        font = QtGui.QFont()
        font.setFamily("roboto")
        font.setPointSize(-1)
        self.nameEdit.setFont(font)
        self.nameEdit.setObjectName("nameEdit")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.yearEdit = QtWidgets.QLineEdit(self.widget)
        self.yearEdit.setGeometry(QtCore.QRect(30, 150, 61, 31))
        font = QtGui.QFont()
        font.setFamily("roboto")
        font.setPointSize(-1)
        self.yearEdit.setFont(font)
        self.yearEdit.setObjectName("yearEdit")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(30, 200, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ratingEdit = QtWidgets.QLineEdit(self.widget)
        self.ratingEdit.setGeometry(QtCore.QRect(30, 530, 341, 31))
        font = QtGui.QFont()
        font.setFamily("roboto")
        font.setPointSize(-1)
        self.ratingEdit.setFont(font)
        self.ratingEdit.setObjectName("ratingEdit")
        self.countryEdit = QtWidgets.QLineEdit(self.widget)
        self.countryEdit.setGeometry(QtCore.QRect(30, 240, 341, 31))
        font = QtGui.QFont()
        font.setFamily("roboto")
        font.setPointSize(-1)
        self.countryEdit.setFont(font)
        self.countryEdit.setObjectName("countryEdit")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(30, 490, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.genreEdit = QtWidgets.QLineEdit(self.widget)
        self.genreEdit.setGeometry(QtCore.QRect(30, 330, 341, 31))
        font = QtGui.QFont()
        font.setFamily("roboto")
        font.setPointSize(-1)
        self.genreEdit.setFont(font)
        self.genreEdit.setObjectName("genreEdit")

        self.retranslateUi(AddDialog)
        QtCore.QMetaObject.connectSlotsByName(AddDialog)

    def retranslateUi(self, AddDialog):
        _translate = QtCore.QCoreApplication.translate
        AddDialog.setWindowTitle(_translate("AddDialog", "Dialog"))
        self.addButton.setText(_translate("AddDialog", "Добавить"))
        self.label_5.setText(_translate("AddDialog", "Режиссер"))
        self.label_4.setText(_translate("AddDialog", "Жанр"))
        self.label.setText(_translate("AddDialog", "Название"))
        self.label_2.setText(_translate("AddDialog", "Год выпуска"))
        self.label_3.setText(_translate("AddDialog", "Страна производства"))
        self.label_6.setText(_translate("AddDialog", "Рейтинг"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddDialog = QtWidgets.QDialog()
    ui = Ui_AddDialog()
    ui.setupUi(AddDialog)
    AddDialog.show()
    sys.exit(app.exec())
