# Form implementation generated from reading ui file 'delete_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeleteDialog(object):
    def setupUi(self, DeleteDialog):
        DeleteDialog.setObjectName("DeleteDialog")
        DeleteDialog.resize(400, 196)
        self.deleteEdit = QtWidgets.QLineEdit(DeleteDialog)
        self.deleteEdit.setGeometry(QtCore.QRect(10, 60, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.deleteEdit.setFont(font)
        self.deleteEdit.setObjectName("deleteEdit")
        self.deleteButton = QtWidgets.QPushButton(DeleteDialog)
        self.deleteButton.setGeometry(QtCore.QRect(110, 130, 181, 41))
        self.deleteButton.setObjectName("deleteButton")

        self.retranslateUi(DeleteDialog)
        QtCore.QMetaObject.connectSlotsByName(DeleteDialog)

    def retranslateUi(self, DeleteDialog):
        _translate = QtCore.QCoreApplication.translate
        DeleteDialog.setWindowTitle(_translate("DeleteDialog", "Dialog"))
        self.deleteEdit.setPlaceholderText(_translate("DeleteDialog", "Название"))
        self.deleteButton.setText(_translate("DeleteDialog", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteDialog = QtWidgets.QDialog()
    ui = Ui_DeleteDialog()
    ui.setupUi(DeleteDialog)
    DeleteDialog.show()
    sys.exit(app.exec())
