# Form implementation generated from reading ui file 'find_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 160)
        self.findEdit = QtWidgets.QLineEdit(Dialog)
        self.findEdit.setGeometry(QtCore.QRect(50, 20, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.findEdit.setFont(font)
        self.findEdit.setObjectName("findEdit")
        self.findButton = QtWidgets.QPushButton(Dialog)
        self.findButton.setGeometry(QtCore.QRect(120, 90, 171, 41))
        self.findButton.setObjectName("findButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.findEdit.setPlaceholderText(_translate("Dialog", "Поиск"))
        self.findButton.setText(_translate("Dialog", "Найти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
