# Form implementation generated from reading ui file 'find_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FindDialog(object):
    def setupUi(self, FindDialog):
        FindDialog.setObjectName("FindDialog")
        FindDialog.resize(400, 160)
        self.findEdit = QtWidgets.QLineEdit(FindDialog)
        self.findEdit.setGeometry(QtCore.QRect(50, 20, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.findEdit.setFont(font)
        self.findEdit.setObjectName("findEdit")
        self.findButton = QtWidgets.QPushButton(FindDialog)
        self.findButton.setGeometry(QtCore.QRect(120, 90, 171, 41))
        self.findButton.setObjectName("findButton")

        self.retranslateUi(FindDialog)
        QtCore.QMetaObject.connectSlotsByName(FindDialog)

    def retranslateUi(self, FindDialog):
        _translate = QtCore.QCoreApplication.translate
        FindDialog.setWindowTitle(_translate("FindDialog", "Dialog"))
        self.findEdit.setPlaceholderText(_translate("FindDialog", "Поиск"))
        self.findButton.setText(_translate("FindDialog", "Найти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FindDialog = QtWidgets.QDialog()
    ui = Ui_FindDialog()
    ui.setupUi(FindDialog)
    FindDialog.show()
    sys.exit(app.exec())
