# Form implementation generated from reading ui file 'sub_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SubDialog(object):
    def setupUi(self, SubDialog):
        SubDialog.setObjectName("SubDialog")
        SubDialog.resize(515, 300)
        self.buyButton = QtWidgets.QPushButton(SubDialog)
        self.buyButton.setGeometry(QtCore.QRect(20, 200, 151, 51))
        self.buyButton.setObjectName("buyButton")
        self.status_label = QtWidgets.QLabel(SubDialog)
        self.status_label.setGeometry(QtCore.QRect(30, 10, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.until_label = QtWidgets.QLabel(SubDialog)
        self.until_label.setGeometry(QtCore.QRect(30, 80, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.until_label.setFont(font)
        self.until_label.setObjectName("until_label")
        self.buyButton_2 = QtWidgets.QPushButton(SubDialog)
        self.buyButton_2.setGeometry(QtCore.QRect(190, 200, 151, 51))
        self.buyButton_2.setObjectName("buyButton_2")
        self.buyButton_3 = QtWidgets.QPushButton(SubDialog)
        self.buyButton_3.setGeometry(QtCore.QRect(360, 200, 151, 51))
        self.buyButton_3.setObjectName("buyButton_3")
        self.label = QtWidgets.QLabel(SubDialog)
        self.label.setGeometry(QtCore.QRect(20, 170, 151, 21))
        self.label.setObjectName("label")

        self.retranslateUi(SubDialog)
        QtCore.QMetaObject.connectSlotsByName(SubDialog)

    def retranslateUi(self, SubDialog):
        _translate = QtCore.QCoreApplication.translate
        SubDialog.setWindowTitle(_translate("SubDialog", "Dialog"))
        self.buyButton.setText(_translate("SubDialog", "1000 руб (1 год)"))
        self.status_label.setText(_translate("SubDialog", "Статус "))
        self.until_label.setText(_translate("SubDialog", "Осталось"))
        self.buyButton_2.setText(_translate("SubDialog", "600 рублей (6 месяцев) "))
        self.buyButton_3.setText(_translate("SubDialog", "150 рублей (1 месяц"))
        self.label.setText(_translate("SubDialog", "Нажмите для продолжения:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SubDialog = QtWidgets.QDialog()
    ui = Ui_SubDialog()
    ui.setupUi(SubDialog)
    SubDialog.show()
    sys.exit(app.exec())
