# Form implementation generated from reading ui file 'login_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(400, 300)
        LoginDialog.setMinimumSize(QtCore.QSize(400, 300))
        LoginDialog.setMaximumSize(QtCore.QSize(400, 300))
        self.widget = QtWidgets.QWidget(LoginDialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.widget.setStyleSheet("QWidget#widget{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 72, 72, 255), stop:1 rgba(136, 129, 255, 255));\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 140, 0, 255), stop:1 rgba(0, 212, 255, 255));\n"
"    border: 2px solid #85efff;\n"
"    border-radius: 15px;    \n"
"    color: rgb(255, 255, 255);\n"
"    font-family: roboto;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 255, 115, 255), stop:1 rgba(184, 255, 73, 255));\n"
"    border: 2px solid #90ff94;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border-radius: 15px;\n"
"    font-family: roboto;\n"
"    font-size: 20px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.passEdit = QtWidgets.QLineEdit(self.widget)
        self.passEdit.setGeometry(QtCore.QRect(150, 140, 241, 31))
        font = QtGui.QFont()
        font.setFamily("roboto")
        font.setPointSize(-1)
        self.passEdit.setFont(font)
        self.passEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passEdit.setObjectName("passEdit")
        self.loginEdit = QtWidgets.QLineEdit(self.widget)
        self.loginEdit.setGeometry(QtCore.QRect(150, 50, 241, 31))
        font = QtGui.QFont()
        font.setFamily("roboto")
        font.setPointSize(-1)
        self.loginEdit.setFont(font)
        self.loginEdit.setObjectName("loginEdit")
        self.logButton = QtWidgets.QPushButton(self.widget)
        self.logButton.setGeometry(QtCore.QRect(20, 230, 161, 41))
        font = QtGui.QFont()
        font.setFamily("roboto")
        font.setPointSize(-1)
        self.logButton.setFont(font)
        self.logButton.setObjectName("logButton")
        self.regButton = QtWidgets.QPushButton(self.widget)
        self.regButton.setGeometry(QtCore.QRect(210, 230, 161, 41))
        font = QtGui.QFont()
        font.setFamily("roboto")
        font.setPointSize(-1)
        self.regButton.setFont(font)
        self.regButton.setObjectName("regButton")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Dialog"))
        self.label.setText(_translate("LoginDialog", "Логин"))
        self.label_2.setText(_translate("LoginDialog", "Пароль"))
        self.logButton.setText(_translate("LoginDialog", "Войти"))
        self.regButton.setText(_translate("LoginDialog", "Регистрация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec())
