# Form implementation generated from reading ui file 'sub_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SubDialog(object):
    def setupUi(self, SubDialog):
        SubDialog.setObjectName("SubDialog")
        SubDialog.resize(515, 300)
        SubDialog.setMinimumSize(QtCore.QSize(515, 300))
        SubDialog.setMaximumSize(QtCore.QSize(515, 300))
        SubDialog.setStyleSheet("")
        self.widget = QtWidgets.QWidget(SubDialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 515, 300))
        self.widget.setMinimumSize(QtCore.QSize(515, 300))
        self.widget.setMaximumSize(QtCore.QSize(515, 300))
        self.widget.setStyleSheet("QWidget#widget{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 72, 72, 255), stop:1 rgba(136, 129, 255, 255));\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 140, 0, 255), stop:1 rgba(0, 212, 255, 255));\n"
"    border: 2px solid #85efff;\n"
"    border-radius: 15px;    \n"
"    color: rgb(255, 255, 255);\n"
"    font-family: roboto;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 255, 115, 255), stop:1 rgba(184, 255, 73, 255));\n"
"    border: 2px solid #90ff94;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border-radius: 15px;\n"
"    font-family: roboto;\n"
"    font-size: 20px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 180, 181, 21))
        self.label.setObjectName("label")
        self.buyButton_3 = QtWidgets.QPushButton(self.widget)
        self.buyButton_3.setGeometry(QtCore.QRect(350, 210, 151, 51))
        self.buyButton_3.setObjectName("buyButton_3")
        self.buyButton_2 = QtWidgets.QPushButton(self.widget)
        self.buyButton_2.setGeometry(QtCore.QRect(180, 210, 151, 51))
        self.buyButton_2.setObjectName("buyButton_2")
        self.buyButton = QtWidgets.QPushButton(self.widget)
        self.buyButton.setGeometry(QtCore.QRect(10, 210, 151, 51))
        self.buyButton.setObjectName("buyButton")
        self.status_label = QtWidgets.QLabel(self.widget)
        self.status_label.setGeometry(QtCore.QRect(30, 20, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.until_label = QtWidgets.QLabel(self.widget)
        self.until_label.setGeometry(QtCore.QRect(30, 90, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.until_label.setFont(font)
        self.until_label.setObjectName("until_label")

        self.retranslateUi(SubDialog)
        QtCore.QMetaObject.connectSlotsByName(SubDialog)

    def retranslateUi(self, SubDialog):
        _translate = QtCore.QCoreApplication.translate
        SubDialog.setWindowTitle(_translate("SubDialog", "Dialog"))
        self.label.setText(_translate("SubDialog", "Нажмите для продолжения:"))
        self.buyButton_3.setText(_translate("SubDialog", "150 рублей (1 месяц"))
        self.buyButton_2.setText(_translate("SubDialog", "600 рублей (6 месяцев) "))
        self.buyButton.setText(_translate("SubDialog", "1000 руб (1 год)"))
        self.status_label.setText(_translate("SubDialog", "Статус "))
        self.until_label.setText(_translate("SubDialog", "Осталось"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SubDialog = QtWidgets.QDialog()
    ui = Ui_SubDialog()
    ui.setupUi(SubDialog)
    SubDialog.show()
    sys.exit(app.exec())
